"""Alembic environment.

Two deliberate choices:

* The DSN comes from the application's typed settings, not from ``alembic.ini``, so
  there is exactly one definition of how to reach the database and no credential in
  a committed file.
* Migrations run **synchronously** via psycopg. Alembic's async recipe adds an event
  loop for no benefit here, and migrations are a serialised, offline operation.

Migrations are executed as the owning role, not as ``app_api``/``app_worker``/
``app_publisher``. Those runtime roles deliberately lack DDL rights; see
``infra/postgres/README.md``.
"""

from __future__ import annotations

import os
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.config import DatabaseRole, get_settings


def _load_repo_dotenv() -> None:
    path = Path(__file__).resolve().parents[3] / ".env"
    if not path.is_file():
        return
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        if key:
            os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


_load_repo_dotenv()
from app.core.db import Base
from app.db.classification import MIGRATION_OWNED_INDEXES

# Imported for its side effect: registers every model on Base.metadata.
from app.db import all_models  # noqa: F401

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

# The domain models are registered by importing app.db.all_models above. The
# constraint naming convention travels with this MetaData object (see core/db.py);
# Alembic reads it from here when rendering autogenerated migrations.
target_metadata = Base.metadata

config.set_main_option("sqlalchemy.url", get_settings().database.sync_dsn(DatabaseRole.MIGRATION))


def include_object(
    obj: object, name: str | None, type_: str, reflected: bool, compare_to: object
) -> bool:
    """Exclude migration-owned indexes from autogenerate comparison.

    Trigram, full-text, range and partial indexes are declared in the search-index
    migration rather than on the models (see app.db.classification). Without this
    hook every `alembic check` would propose dropping them, because they exist in the
    database and not in the metadata -- which would make the drift check useless.
    """
    return not (type_ == "index" and name in MIGRATION_OWNED_INDEXES)


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a database connection (``alembic upgrade --sql``).

    Useful for reviewing DDL before it runs and for validating migrations in CI
    where no database is available.
    """
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        # Detect column type changes; without this a varchar->text change is silent.
        compare_type=True,
        compare_server_default=True,
        include_schemas=False,
        include_object=include_object,
        transaction_per_migration=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Apply migrations against a live database."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
            include_schemas=False,
            include_object=include_object,
            transaction_per_migration=True,
        )
        with context.begin_transaction():
            context.run_migrations()
    connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
