"""A domain decision names the institution whose packet was reviewed, or it is refused.

WHAT WAS WRONG
==============
`source_review.py domain` created `official_domain` rows with `target_institution_id`
left NULL unless `--institution` happened to be passed, and the pilot workflow never
passed it. A verified host would then have sat in the database attached to nothing --
the record of a human decision about *an institution's* web property, with the
institution missing.

It did not break the trust chain: promotion joins `source_mapping.official_domain_id`
and reads `od.verification_status` and `od.is_active`, never the domain row's institution.
That is exactly why this had to be caught by inspection rather than by a failing
promotion -- nothing downstream would ever have complained.

THE MANIFEST IS THE AUTHORITY, NOT THE DATABASE
===============================================
The binding is validated against the **frozen review manifest**, not against whatever
the database happens to relate. Two reasons, and the second is the one that matters:

1. The manifest is what the human actually read. A decision is about the packet that was
   put in front of them, so the tuple that must agree is *(manifest sha, host,
   institution)* -- a matching digest alone is not enough if the command then attaches
   the host to a different institution.

2. **A redirect-only host has no database association at all.** `study.anu.edu.au` has no
   `pilot_collected_source` row -- it was never submitted, only redirected to. Its link
   to ANU exists solely in the manifest row, derived from the page that redirects to it.
   A binding resolved from the database would have to either refuse it or invent the
   association; resolved from the manifest, it is simply a fact that was reviewed.

WHY `match_key` IS A SAFE RESOLUTION PATH
=========================================
The manifest stores the institution as a label, because that is what a reviewer reads.
The label is `target_institution.match_key`, which carries a UNIQUE constraint
(`uq_target_institution_match_key`), so label -> id is deterministic and verified here
rather than assumed. The label is never persisted as authority: it is resolved to the id
and the id is what gets written.

NEVER REASSIGN
==============
A host already bound to institution A is never moved to institution B, silently or
otherwise. Adopting a NULL binding is allowed only because the caller arrives with a
manifest-validated institution and writes an audit entry saying so.
"""

from __future__ import annotations

import hashlib
import json
import uuid
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Any

from sqlalchemy import Connection, text

#: Where the frozen review manifests live. The approved artefacts, never regenerated by
#: the code that applies them.
MANIFEST_DIR = Path(".reports/step-5c5")

#: The domain manifest's basename, without extension.
DOMAIN_MANIFEST = "domain_decisions_proposed"


class ManifestChangedError(RuntimeError):
    """The manifest on disk is not the one that was approved."""


class InstitutionBindingError(RuntimeError):
    """The host, the institution and the approved manifest do not agree."""


class BindingAction(StrEnum):
    """What applying this decision would do to the row's institution binding."""

    CREATE = "CREATE"
    """No row exists. One will be created carrying the resolved institution."""

    KEEP = "KEEP"
    """A row exists and is already bound to this institution. Nothing to change."""

    ADOPT = "ADOPT"
    """A row exists with a NULL binding. It will be set, and the audit will say so."""


@dataclass(frozen=True, slots=True)
class ReviewedHost:
    """One host as the approved manifest describes it, with its institution resolved."""

    host: str
    institution_label: str
    institution_id: uuid.UUID
    reached_only_by_redirect: bool
    manifest_sha256: str
    proposed_status_if_accepted: str


def manifest_digest(rows: list[dict[str, Any]]) -> str:
    """The digest of a manifest's rows.

    Byte-for-byte the serialisation `source_review._require_manifest` uses. Written once
    here and reused rather than reimplemented: computing it a second way is how a check
    starts passing against a hash nobody else would produce -- which happened while
    verifying this very manifest, with `separators=` added by mistake.
    """
    payload = json.dumps(rows, sort_keys=True, ensure_ascii=False, default=str)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def load_domain_manifest(
    *, expect_sha256: str, directory: Path = MANIFEST_DIR
) -> tuple[list[dict[str, Any]], str]:
    """Read the frozen domain manifest and prove it is the approved one.

    `expect_sha256` is required, not optional. An optional digest is a digest that gets
    omitted on the day it matters.
    """
    if not expect_sha256 or not expect_sha256.strip():
        raise ManifestChangedError(
            "REVIEW_MANIFEST_CHANGED: no approved manifest digest was supplied. A pilot "
            "domain decision must name the exact package the reviewer read."
        )
    path = directory / f"{DOMAIN_MANIFEST}.json"
    if not path.exists():
        raise ManifestChangedError(
            f"REVIEW_MANIFEST_CHANGED: {path} does not exist. It is NOT regenerated "
            "automatically -- a manifest rebuilt by the applying code is not a manifest "
            "anybody reviewed."
        )
    envelope = json.loads(path.read_text(encoding="utf-8"))
    rows = list(envelope.get("rows") or [])
    digest = manifest_digest(rows)
    if digest != expect_sha256.strip():
        raise ManifestChangedError(
            "REVIEW_MANIFEST_CHANGED\n"
            f"  approved : {expect_sha256}\n  on disk  : {digest}\n"
            "The package under review is not the one being applied."
        )
    return rows, digest


def resolve_institution(connection: Connection, label: str) -> uuid.UUID:
    """Turn the manifest's institution label into the id that gets written.

    `target_institution.match_key` is UNIQUE, so this is deterministic. Refuses rather
    than guessing when the label names nothing: a decision that cannot be attributed is
    not a decision worth storing.
    """
    found = connection.execute(
        text("SELECT id FROM target_institution WHERE match_key = :label"),
        {"label": label},
    ).all()
    if not found:
        raise InstitutionBindingError(
            f"the manifest names institution {label!r}, which matches no "
            "target_institution.match_key. The manifest and the target list disagree."
        )
    if len(found) > 1:
        # Cannot happen while the UNIQUE constraint stands. Checked anyway, because the
        # whole point of this module is that the binding is exact.
        raise InstitutionBindingError(
            f"institution label {label!r} resolves to {len(found)} rows; it must be one"
        )
    return uuid.UUID(str(found[0].id))


def reviewed_host(
    connection: Connection,
    *,
    host: str,
    expect_sha256: str,
    directory: Path = MANIFEST_DIR,
) -> ReviewedHost:
    """Find this host in the approved manifest and resolve the institution it belongs to.

    Works for a redirect-only host: the manifest carries its institution even though no
    `pilot_collected_source` row does, which is the only reason such a host can be
    verified at all.
    """
    rows, digest = load_domain_manifest(expect_sha256=expect_sha256, directory=directory)
    target = host.strip().lower()
    matches = [row for row in rows if str(row.get("host", "")).strip().lower() == target]
    if not matches:
        raise InstitutionBindingError(
            f"{host} does not appear in the approved domain manifest ({digest[:12]}...). "
            "Only hosts the reviewer was actually shown may be decided from it."
        )
    if len(matches) > 1:
        raise InstitutionBindingError(
            f"{host} appears {len(matches)} times in the approved manifest; it must "
            "appear once, or 'the reviewed row' is ambiguous."
        )
    row = matches[0]
    label = str(row.get("institution") or "").strip()
    if not label:
        raise InstitutionBindingError(
            f"the approved manifest row for {host} names no institution, so the decision "
            "cannot be attributed to one."
        )
    return ReviewedHost(
        host=target,
        institution_label=label,
        institution_id=resolve_institution(connection, label),
        reached_only_by_redirect=bool(row.get("reached_only_by_redirect")),
        manifest_sha256=digest,
        proposed_status_if_accepted=str(row.get("proposed_status_if_accepted") or ""),
    )


def require_binding(
    connection: Connection,
    *,
    host: str,
    institution_id: uuid.UUID | None,
    expect_sha256: str,
    directory: Path = MANIFEST_DIR,
) -> ReviewedHost:
    """The whole tuple: approved manifest, host in it, and the institution it names.

    A matching digest is not sufficient on its own. Somebody holding a genuinely approved
    ANU package must not be able to spend that approval on a host reviewed for another
    institution, nor attach an ANU host to another institution's id -- both of which are
    just a different `--institution-id` away if only the digest is checked.
    """
    reviewed = reviewed_host(
        connection, host=host, expect_sha256=expect_sha256, directory=directory
    )
    if institution_id is None:
        raise InstitutionBindingError(
            f"a pilot domain decision for {reviewed.host} must name the institution it "
            f"belongs to. The approved manifest says {reviewed.institution_label!r} "
            f"({reviewed.institution_id}). Pass --institution-id."
        )
    if institution_id != reviewed.institution_id:
        raise InstitutionBindingError(
            f"institution mismatch for {reviewed.host}: the approved manifest reviews it "
            f"under {reviewed.institution_label!r} ({reviewed.institution_id}), and "
            f"{institution_id} was supplied. A decision cannot be moved between "
            "institutions."
        )
    return reviewed


def plan_binding(connection: Connection, *, host: str, institution_id: uuid.UUID) -> BindingAction:
    """What applying this decision would do to the row's institution binding.

    Refuses a reassignment outright. A host bound to institution A never becomes
    institution B's, because the audit trail would then contain a verification that
    somebody made about a different institution's property.
    """
    row = connection.execute(
        text("SELECT id, target_institution_id FROM official_domain WHERE host = :host"),
        {"host": host.strip().lower()},
    ).one_or_none()
    if row is None:
        return BindingAction.CREATE
    if row.target_institution_id is None:
        # Permitted only because the caller reached here with a manifest-validated
        # institution, and the adoption is recorded in the audit entry.
        return BindingAction.ADOPT
    if uuid.UUID(str(row.target_institution_id)) != institution_id:
        raise InstitutionBindingError(
            f"INSTITUTION_BINDING_CONFLICT: {host} is already bound to "
            f"{row.target_institution_id} and the decision names {institution_id}. "
            "A domain is never reassigned from one institution to another."
        )
    return BindingAction.KEEP


__all__ = [
    "DOMAIN_MANIFEST",
    "MANIFEST_DIR",
    "BindingAction",
    "InstitutionBindingError",
    "ManifestChangedError",
    "ReviewedHost",
    "load_domain_manifest",
    "manifest_digest",
    "plan_binding",
    "require_binding",
    "resolve_institution",
    "reviewed_host",
]
