"""Write the OpenAPI document generated by FastAPI to disk.

FastAPI/Pydantic is the single source of truth for the API contract
(ARCHITECTURE.md D10). This script is the first half of the pipeline:

    FastAPI app -> openapi.json -> openapi-typescript -> packages/api-types

Run via ``make generate-api-types`` (or ``pnpm generate:api-types``), never by hand.

The output is written with sorted keys and a trailing newline so the file is stable
across runs; CI compares a freshly generated document against the committed one to
detect stale types, and unstable key ordering would make that check useless.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

# Never read a developer's local .env when generating a contract: the document must
# depend only on the code. Forcing a known environment also keeps /openapi.json
# enabled, which production disables.
DEFAULT_OUTPUT = Path(__file__).resolve().parents[3] / "packages" / "api-types" / "openapi.json"


def build_document() -> dict[str, Any]:
    from app.core.config import Environment, Settings
    from app.main import create_app

    settings = Settings(environment=Environment.CI, log_format="console")
    app = create_app(settings)
    document: dict[str, Any] = app.openapi()
    return document


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT, help="Destination openapi.json path"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the file on disk differs from the generated document",
    )
    args = parser.parse_args()

    rendered = json.dumps(build_document(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"

    if args.check:
        if not args.output.exists():
            print(f"FAIL: {args.output} does not exist; run generate-api-types", file=sys.stderr)
            return 1
        if args.output.read_text(encoding="utf-8") != rendered:
            print(
                f"FAIL: {args.output} is stale; run generate-api-types and commit the result",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {args.output} is up to date")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
